### ISSUE TITLE
Unretrieved `httpx.ConnectTimeout` raised during fragment download

### ISSUE THREAD

**Issue by nosoop** [nosoop/moonarchive#7]
Pending investigation.

It sounds like this is happening due to an exception being thrown elsewhere since it's clearly happening outside of the fragment retrieval operation), but the logs produced by `journalctl` / `hypercorn` aren't particularly telling in this case.

```
Executing <Task pending name='Task-3698537' coro=<stream_downloader() running at ... took 0.111 seconds
--- [two minutes pass] ---
Task exception was never retrieved
future: <Task finished name='Task-3711576' coro=<AsyncClient.get() done, defined at /moombox/.venv/lib/python3.11/site-packages/httpx/_client.py:1797> exception=ConnectTimeout('') exception=ConnectTimeout('') created at /python3.11/asyncio/tasks.py:374>
source_traceback: Object created at (most recent call last):
  File "<string>", line 1, in <module>
  File "/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/python3.11/multiprocessing/spawn.py", line 133, in _main
    return self._bootstrap(parent_sentinel)
  File "/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/moombox/.venv/lib/python3.11/site-packages/hypercorn/asyncio/run.py", line 196, in asyncio_worker
    _run(
  File "/moombox/.venv/lib/python3.11/site-packages/hypercorn/asyncio/run.py", line 234, in _run
    runner.run(main(shutdown_trigger=shutdown_trigger))
  File "/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/python3.11/asyncio/base_events.py", line 1914, in _run_once
    handle._run()
  File "/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/moombox/.venv/lib/python3.11/site-packages/moonarchive/downloaders/youtube.py", line 369, in frag_iterator
    reqs = [
  File "/moombox/.venv/lib/python3.11/site-packages/moonarchive/downloaders/youtube.py", line 373, in <listcomp>
    asyncio.create_task(
  File "/python3.11/asyncio/tasks.py", line 374, in create_task
    task = loop.create_task(coro)
Traceback (most recent call last):
  File "/moombox/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/moombox/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/moombox/.venv/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/moombox/.venv/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/moombox/.venv/lib/python3.11/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/moombox/.venv/lib/python3.11/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/moombox/.venv/lib/python3.11/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/moombox/.venv/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/moombox/.venv/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 115, in connect_tcp
    with map_exceptions(exc_map):
  File "/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/moombox/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/moombox/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1814, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/moombox/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1585, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/moombox/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/moombox/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/moombox/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/moombox/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/moombox/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
    with map_httpcore_exceptions():
  File "/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/moombox/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
--- [no further messages until 20 minutes later for a normal HTTP request] ---
```

Possible culprit off the top of my head is the DASH manifest fetch operation here, since that's the only thing that doesn't have robust exception handling: https://github.com/nosoop/moonarchive/blob/4aca606a778b758b059f6eedd15309e0cb22ffd8/src/moonarchive/models/youtube_player.py#L134-L139

**Comment by nosoop** [comment]
Traceback nailed it; it's indeed a `httpx.ConnectTimeout` on the DASH manifest fetch operation.
